name: 📥 Download Firmware (No Git needed)

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: '输入运行ID'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts using official action
        uses: actions/download-artifact@v4
        with:
          name: OpenWrt-23.05-RAX3000Q-iStoreOS  # 如果知道具体名字就填，不知道就不填
          path: firmware/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: tiegenb/Actions-iStoreOS-RAX3000Q
          run-id: ${{ github.event.inputs.run_id }}
          
      - name: List downloaded files
        run: ls -la firmware/
        
      - name: Upload as new artifact
        uses: actions/upload-artifact@v6
        with:
          name: Downloaded-Firmware
          path: firmware/
